const crypto = require('crypto');
const express = require('express');
const { Prisma } = require('@prisma/client');
const prisma = require('../prisma');
const { asyncHandler, HttpError } = require('../utils/http');
const { requireAdmin } = require('../middleware/auth');
const { upload, uploadedFileValue, isBase64DataUrl } = require('../utils/upload');
const { publicUser } = require('../middleware/auth');
const { boolFromBody, productListSerializer, productDetailSerializer, categorySerializer, brandSerializer, orderSerializer, couponSerializer, reviewSerializer } = require('../utils/serializers');

const router = express.Router();
router.use(requireAdmin);

function slugify(value) {
    return String(value || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || `item-${Date.now()}`;
}

async function uniqueProductSlug(name, id) {
    const base = slugify(name);
    let slug = base;
    let counter = 1;
    while (await prisma.product.findFirst({ where: { slug, ...(id ? { NOT: { id } } : {}) } })) slug = `${base}-${counter++}`;
    return slug;
}

function productInclude() {
    return { category: true, brand: true, reviews: true, variants: true, galleryImages: { orderBy: { sortOrder: 'asc' } } };
}

function randomCode(prefix = 'GIFT', length = 12) {
    const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    let code = '';
    while (code.length < length) code += alphabet[crypto.randomInt(0, alphabet.length)];
    return `${prefix}-${code}`;
}

function decimalInput(value, fallback = 0) {
    return new Prisma.Decimal(value === undefined || value === null || value === '' ? fallback : value);
}

async function createCouponFromBody(body, extra = {}) {
    const validDays = Number(body.valid_days || 30);
    const code = body.code || randomCode(body.is_gift || body.generate_token ? 'GIFT' : 'COUPON', Number(body.token_length || 12));
    return prisma.coupon.create({
        data: {
            code: String(code).toUpperCase(),
            discountType: body.discount_type || 'percentage',
            discountValue: decimalInput(body.discount_value),
            minOrderAmount: decimalInput(body.min_order_amount),
            maxUses: Number(body.max_uses || 1),
            isActive: boolFromBody(body.is_active, true),
            validFrom: body.valid_from ? new Date(body.valid_from) : new Date(),
            validTo: body.valid_to ? new Date(body.valid_to) : new Date(Date.now() + validDays * 86400000),
            assignedToId: body.assigned_to ? Number(body.assigned_to) : null,
            isGift: boolFromBody(body.is_gift || body.generate_token, false),
            autoGenerated: boolFromBody(body.auto_generated || body.generate_token || body.bulk_count || body.assign_to_all, false),
            description: body.description || '',
            ...extra,
        },
    });
}

function monthKey(date) {
    const d = new Date(date);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
}

router.get('/dashboard/', asyncHandler(async (req, res) => {
    const [totalProducts, totalUsers, totalOrders, revenue, pendingOrders, pendingPayments, lowStock, recentOrders] = await Promise.all([
        prisma.product.count(), prisma.user.count(), prisma.order.count(), prisma.order.aggregate({ _sum: { paidAmount: true } }),
        prisma.order.count({ where: { orderStatus: 'Processing' } }), prisma.order.count({ where: { paymentStatus: 'Pending' } }),
        prisma.product.count({ where: { stock: { lte: 5 } } }), prisma.order.findMany({ include: { user: true, coupon: true, items: { include: { product: true } } }, orderBy: { createdAt: 'desc' }, take: 10 }),
    ]);
    res.json({ total_products: totalProducts, total_users: totalUsers, total_orders: totalOrders, total_revenue: Number(revenue._sum.paidAmount || 0), total_profit: 0, pending_orders: pendingOrders, pending_payments: pendingPayments, low_stock: lowStock, recent_orders: recentOrders.map(orderSerializer) });
}));

router.get('/products/', asyncHandler(async (req, res) => {
    const where = {};
    if (req.query.search) where.OR = [{ name: { contains: String(req.query.search), mode: 'insensitive' } }, { tags: { contains: String(req.query.search), mode: 'insensitive' } }];
    if (req.query.status) where.status = req.query.status === 'active';
    const products = await prisma.product.findMany({ where, include: productInclude(), orderBy: { createdAt: 'desc' } });
    res.json(products.map(productListSerializer));
}));

router.post('/products/', upload.single('image'), asyncHandler(async (req, res) => {
    if (!req.body.name) throw new HttpError(400, 'Name is required');
    const image = req.file ? uploadedFileValue(req.file) : (!isBase64DataUrl(req.body.image) ? (req.body.image || '') : '');
    const product = await prisma.product.create({
        data: {
            name: req.body.name, slug: await uniqueProductSlug(req.body.name), description: req.body.description || '', price: new Prisma.Decimal(req.body.price || 0),
            comparePrice: req.body.compare_price ? new Prisma.Decimal(req.body.compare_price) : null, retailPrice: new Prisma.Decimal(req.body.retail_price || 0), stock: Number(req.body.stock || 0),
            categoryId: req.body.category ? Number(req.body.category) : null, brandId: req.body.brand ? Number(req.body.brand) : null, image,
            status: boolFromBody(req.body.status, true), isFeatured: boolFromBody(req.body.is_featured), hasVariants: boolFromBody(req.body.has_variants), freeDelivery: boolFromBody(req.body.free_delivery),
            minQuantity: Number(req.body.min_quantity || 1), deliveryCharge: new Prisma.Decimal(req.body.delivery_charge || 0), tags: req.body.tags || '', specifications: req.body.specifications || undefined,
            metaTitle: req.body.meta_title || '', metaDescription: req.body.meta_description || '', metaKeywords: req.body.meta_keywords || '',
        }, include: productInclude()
    });
    res.status(201).json(productDetailSerializer(product));
}));

router.get('/products/:id/', asyncHandler(async (req, res) => {
    const product = await prisma.product.findUnique({ where: { id: Number(req.params.id) }, include: productInclude() });
    if (!product) throw new HttpError(404, 'Not found');
    res.json(productDetailSerializer(product));
}));

router.patch('/products/:id/', upload.single('image'), asyncHandler(async (req, res) => {
    const id = Number(req.params.id);
    const data = {};
    for (const key of ['name', 'description', 'tags']) if (key in req.body) data[key] = req.body[key];
    if ('name' in data) data.slug = await uniqueProductSlug(data.name, id);
    if ('price' in req.body) data.price = new Prisma.Decimal(req.body.price || 0);
    if ('compare_price' in req.body) data.comparePrice = req.body.compare_price ? new Prisma.Decimal(req.body.compare_price) : null;
    if ('retail_price' in req.body) data.retailPrice = new Prisma.Decimal(req.body.retail_price || 0);
    if ('stock' in req.body) data.stock = Number(req.body.stock || 0);
    if ('category' in req.body) data.categoryId = req.body.category ? Number(req.body.category) : null;
    if ('brand' in req.body) data.brandId = req.body.brand ? Number(req.body.brand) : null;
    if ('status' in req.body) data.status = boolFromBody(req.body.status);
    for (const [body, db] of [['is_featured', 'isFeatured'], ['has_variants', 'hasVariants'], ['free_delivery', 'freeDelivery']]) if (body in req.body) data[db] = boolFromBody(req.body[body]);
    if ('min_quantity' in req.body) data.minQuantity = Number(req.body.min_quantity || 1);
    if ('delivery_charge' in req.body) data.deliveryCharge = new Prisma.Decimal(req.body.delivery_charge || 0);
    if ('meta_title' in req.body) data.metaTitle = req.body.meta_title;
    if ('meta_description' in req.body) data.metaDescription = req.body.meta_description;
    if ('meta_keywords' in req.body) data.metaKeywords = req.body.meta_keywords;
    if ('image_alt' in req.body) data.imageAlt = req.body.image_alt;
    if (req.file) data.image = uploadedFileValue(req.file); else if (req.body.image && !isBase64DataUrl(req.body.image)) data.image = req.body.image;
    const product = await prisma.product.update({ where: { id }, data, include: productInclude() });
    res.json(productDetailSerializer(product));
}));

router.delete('/products/:id/', asyncHandler(async (req, res) => {
    await prisma.product.delete({ where: { id: Number(req.params.id) } });
    res.json({ message: 'Product deleted' });
}));

router.get('/categories/', asyncHandler(async (req, res) => {
    const rows = await prisma.category.findMany({ include: { _count: { select: { products: true } } }, orderBy: { sortOrder: 'asc' } });
    res.json(rows.map(categorySerializer));
}));

router.post('/categories/', upload.single('image'), asyncHandler(async (req, res) => {
    if (!req.body.name) throw new HttpError(400, 'Name is required');
    const row = await prisma.category.create({ data: { name: req.body.name, description: req.body.description || '', image: req.file ? uploadedFileValue(req.file) : (req.body.image || ''), sortOrder: Number(req.body.sort_order || 0), discountPercentage: new Prisma.Decimal(req.body.discount_percentage || 0), isActive: boolFromBody(req.body.is_active, true) }, include: { _count: { select: { products: true } } } });
    res.status(201).json(categorySerializer(row));
}));

router.patch('/categories/:id/', asyncHandler(async (req, res) => {
    const data = {};
    if ('name' in req.body) data.name = req.body.name;
    if ('description' in req.body) data.description = req.body.description;
    if ('sort_order' in req.body) data.sortOrder = Number(req.body.sort_order || 0);
    if ('discount_percentage' in req.body) data.discountPercentage = new Prisma.Decimal(req.body.discount_percentage || 0);
    if ('is_active' in req.body) data.isActive = boolFromBody(req.body.is_active);
    if ('image' in req.body && !isBase64DataUrl(req.body.image)) data.image = req.body.image;
    const row = await prisma.category.update({ where: { id: Number(req.params.id) }, data, include: { _count: { select: { products: true } } } });
    res.json(categorySerializer(row));
}));

router.delete('/categories/:id/', asyncHandler(async (req, res) => { await prisma.category.delete({ where: { id: Number(req.params.id) } }); res.status(204).send(); }));
router.get('/brands/', asyncHandler(async (req, res) => { const rows = await prisma.brand.findMany({ include: { _count: { select: { products: true } } }, orderBy: { name: 'asc' } }); res.json(rows.map(brandSerializer)); }));

router.get('/orders/', asyncHandler(async (req, res) => {
    const where = {};
    if (req.query.payment_status) where.paymentStatus = req.query.payment_status;
    if (req.query.order_status) where.orderStatus = req.query.order_status;
    const rows = await prisma.order.findMany({ where, include: { user: true, coupon: true, items: { include: { product: true } } }, orderBy: { createdAt: 'desc' } });
    res.json(rows.map(orderSerializer));
}));
router.post('/orders/create/', asyncHandler(async (req, res) => {
    const items = Array.isArray(req.body.items) ? req.body.items : [];
    if (!items.length) throw new HttpError(400, 'At least one product is required');
    if (!req.body.customer_name && !req.body.user_id) throw new HttpError(400, 'Customer name or user is required');

    const user = req.body.user_id ? await prisma.user.findUnique({ where: { id: Number(req.body.user_id) } }) : null;
    if (req.body.user_id && !user) throw new HttpError(404, 'User not found');

    const resolvedItems = [];
    let subtotal = new Prisma.Decimal(0);
    for (const [idx, item] of items.entries()) {
        if (!item.product_id) throw new HttpError(400, `Item ${idx}: product_id is required`);
        const product = await prisma.product.findFirst({ where: { id: Number(item.product_id), status: true } });
        if (!product) throw new HttpError(404, `Item ${idx}: Product #${item.product_id} not found`);
        const quantity = Math.max(1, Number(item.quantity || 1));
        const price = decimalInput(item.price, product.price);
        const total = price.mul(quantity);
        subtotal = subtotal.add(total);
        resolvedItems.push({ product, quantity, price, total });
    }

    const shippingCost = decimalInput(req.body.shipping_cost);
    const discountAmount = decimalInput(req.body.discount_amount);
    const grandTotal = Prisma.Decimal.max(subtotal.add(shippingCost).sub(discountAmount), new Prisma.Decimal(0));
    const paidAmount = decimalInput(req.body.paid_amount);
    const dueAmount = Prisma.Decimal.max(grandTotal.sub(paidAmount), new Prisma.Decimal(0));
    const manualNotes = !user && req.body.customer_name ? `[Manual Order] Customer: ${req.body.customer_name}${req.body.customer_email ? ` | Email: ${req.body.customer_email}` : ''}${req.body.customer_phone ? ` | Phone: ${req.body.customer_phone}` : ''}\n` : '';

    const order = await prisma.$transaction(async (tx) => {
        const created = await tx.order.create({
            data: {
                userId: user?.id || req.user.id,
                customerName: req.body.customer_name || '',
                customerEmail: req.body.customer_email || '',
                shippingAddress: req.body.shipping_address || '',
                city: req.body.city || '',
                phone: req.body.customer_phone || '',
                total: grandTotal,
                subtotal,
                discountAmount,
                shippingCost,
                paidAmount,
                dueAmount,
                paymentMethod: req.body.payment_method || 'Cash on Delivery',
                paymentStatus: req.body.payment_status || 'Unpaid',
                orderStatus: req.body.order_status || 'Pending',
                trackingNumber: req.body.tracking_number || '',
                notes: `${manualNotes}${req.body.notes || ''}`.trim(),
                items: { create: resolvedItems.map((item) => ({ productId: item.product.id, quantity: item.quantity, price: item.price, total: item.total })) },
            },
            include: { user: true, coupon: true, items: { include: { product: true } } },
        });
        for (const item of resolvedItems) await tx.product.update({ where: { id: item.product.id }, data: { stock: { decrement: item.quantity } } });
        if (user) await tx.userNotification.create({ data: { userId: user.id, subject: 'New Order Created (Admin)', body: `An order #${created.id} has been created for you by the admin. Total: RS ${Number(grandTotal).toLocaleString()}` } });
        return created;
    });

    res.status(201).json(orderSerializer(order));
}));
router.get('/orders/:id/', asyncHandler(async (req, res) => { const row = await prisma.order.findUnique({ where: { id: Number(req.params.id) }, include: { user: true, coupon: true, items: { include: { product: true } } } }); if (!row) throw new HttpError(404, 'Not found'); res.json(orderSerializer(row)); }));
router.post('/orders/:id/status/', asyncHandler(async (req, res) => {
    const data = {};
    if (req.body.status) data.orderStatus = req.body.status;
    if ('payment_status' in req.body) data.paymentStatus = req.body.payment_status;
    if ('tracking_number' in req.body) data.trackingNumber = req.body.tracking_number;
    if ('notes' in req.body) data.notes = req.body.notes;
    if ('paid_amount' in req.body) data.paidAmount = new Prisma.Decimal(req.body.paid_amount || 0);
    const row = await prisma.order.update({ where: { id: Number(req.params.id) }, data, include: { user: true, coupon: true, items: { include: { product: true } } } });
    res.json(orderSerializer(row));
}));
router.delete('/orders/:id/delete/', asyncHandler(async (req, res) => {
    const id = Number(req.params.id);
    await prisma.$transaction(async (tx) => {
        const order = await tx.order.findUnique({ where: { id }, include: { items: true } });
        if (!order) throw new HttpError(404, 'Order not found');
        for (const item of order.items) {
            if (item.productId) await tx.product.update({ where: { id: item.productId }, data: { stock: { increment: item.quantity } } });
        }
        if (order.couponId) await tx.coupon.update({ where: { id: order.couponId }, data: { usedCount: { decrement: 1 } } }).catch(() => null);
        await tx.orderItem.deleteMany({ where: { orderId: id } });
        await tx.order.delete({ where: { id } });
    });
    res.json({ message: 'Order deleted and stock reversed' });
}));

router.get('/users/', asyncHandler(async (req, res) => { const where = req.query.search ? { OR: [{ email: { contains: String(req.query.search), mode: 'insensitive' } }, { phone: { contains: String(req.query.search), mode: 'insensitive' } }] } : {}; const users = await prisma.user.findMany({ where, include: { _count: { select: { orders: true } } }, orderBy: { dateJoined: 'desc' } }); res.json(users.map(publicUser)); }));
router.get('/users/:id/', asyncHandler(async (req, res) => { const user = await prisma.user.findUnique({ where: { id: Number(req.params.id) }, include: { _count: { select: { orders: true } } } }); const orders = await prisma.order.findMany({ where: { userId: Number(req.params.id) }, include: { user: true, coupon: true, items: { include: { product: true } } }, orderBy: { createdAt: 'desc' } }); res.json({ user: publicUser(user), orders: orders.map(orderSerializer) }); }));
router.post('/users/:id/toggle/', asyncHandler(async (req, res) => { const user = await prisma.user.update({ where: { id: Number(req.params.id) }, data: { isSuspended: { set: !(await prisma.user.findUnique({ where: { id: Number(req.params.id) } })).isSuspended } } }); res.json({ message: `User ${user.isSuspended ? 'suspended' : 'activated'}`, is_suspended: user.isSuspended }); }));

router.get('/reviews/', asyncHandler(async (req, res) => { const rows = await prisma.review.findMany({ include: { user: true, product: true }, orderBy: { createdAt: 'desc' } }); res.json(rows.map(reviewSerializer)); }));
router.post('/reviews/', asyncHandler(async (req, res) => { const id = Number(req.body.review_id); if (req.body.action === 'delete') { await prisma.review.delete({ where: { id } }); return res.json({ message: 'Review deleted' }); } const row = await prisma.review.update({ where: { id }, data: { isApproved: req.body.action === 'approve' } }); res.json({ message: row.isApproved ? 'Review approved' : 'Review rejected' }); }));

router.get('/settings/', asyncHandler(async (req, res) => { const rows = await prisma.setting.findMany(); res.json(Object.fromEntries(rows.map((row) => [row.key, row.value]))); }));
router.post('/settings/', upload.any(), asyncHandler(async (req, res) => { for (const file of req.files || []) await prisma.setting.upsert({ where: { key: file.fieldname }, create: { key: file.fieldname, value: uploadedFileValue(file) }, update: { value: uploadedFileValue(file) } }); for (const [key, value] of Object.entries(req.body || {})) if (value) await prisma.setting.upsert({ where: { key }, create: { key, value: String(value) }, update: { value: String(value) } }); res.json({ message: 'Settings saved' }); }));
router.get('/seo/', asyncHandler(async (req, res) => { const keys = ['site_title', 'meta_description', 'meta_keywords', 'og_image', 'og_title', 'og_description', 'canonical_url', 'google_analytics_id']; const rows = await prisma.setting.findMany({ where: { key: { in: keys } } }); const data = Object.fromEntries(keys.map((key) => [key, ''])); for (const row of rows) data[row.key] = row.value; res.json(data); }));
router.post('/seo/', asyncHandler(async (req, res) => { for (const [key, value] of Object.entries(req.body || {})) await prisma.setting.upsert({ where: { key }, create: { key, value: String(value) }, update: { value: String(value) } }); res.json({ message: 'SEO settings saved' }); }));

function bannerPayload(row) {
    return { id: row.id, image: row.image, title: row.title, subtitle: row.subtitle, link_url: row.linkUrl, banner_type: row.bannerType, active: row.active, sort_order: row.sortOrder, product: row.productId, created_at: row.createdAt, updated_at: row.updatedAt };
}

router.get('/products/:productId/variants/', asyncHandler(async (req, res) => {
    const rows = await prisma.productVariant.findMany({ where: { productId: Number(req.params.productId) }, include: { product: true }, orderBy: [{ size: 'asc' }, { color: 'asc' }] });
    res.json(rows.map((row) => ({ id: row.id, size: row.size, color: row.color, color_code: row.colorCode, sku: row.sku, price_override: row.priceOverride, effective_price: row.priceOverride || row.product.price, stock: row.stock, image: row.image, is_active: row.isActive })));
}));
router.post('/products/:productId/variants/', upload.single('image'), asyncHandler(async (req, res) => {
    const row = await prisma.productVariant.create({ data: { productId: Number(req.params.productId), size: req.body.size || '', color: req.body.color || '', colorCode: req.body.color_code || '', sku: req.body.sku || `${req.params.productId}-${Date.now()}`, priceOverride: req.body.price_override ? new Prisma.Decimal(req.body.price_override) : null, stock: Number(req.body.stock || 0), image: req.file ? uploadedFileValue(req.file) : (req.body.image || ''), isActive: boolFromBody(req.body.is_active, true) }, include: { product: true } });
    res.status(201).json({ id: row.id, size: row.size, color: row.color, color_code: row.colorCode, sku: row.sku, price_override: row.priceOverride, effective_price: row.priceOverride || row.product.price, stock: row.stock, image: row.image, is_active: row.isActive });
}));
router.patch('/products/:productId/variants/:variantId/', upload.single('image'), asyncHandler(async (req, res) => {
    const data = {};
    if ('size' in req.body) data.size = req.body.size;
    if ('color' in req.body) data.color = req.body.color;
    if ('color_code' in req.body) data.colorCode = req.body.color_code;
    if ('sku' in req.body) data.sku = req.body.sku;
    if ('price_override' in req.body) data.priceOverride = req.body.price_override ? new Prisma.Decimal(req.body.price_override) : null;
    if ('stock' in req.body) data.stock = Number(req.body.stock || 0);
    if ('is_active' in req.body) data.isActive = boolFromBody(req.body.is_active);
    if (req.file) data.image = uploadedFileValue(req.file);
    const row = await prisma.productVariant.update({ where: { id: Number(req.params.variantId) }, data, include: { product: true } });
    res.json({ id: row.id, size: row.size, color: row.color, color_code: row.colorCode, sku: row.sku, price_override: row.priceOverride, effective_price: row.priceOverride || row.product.price, stock: row.stock, image: row.image, is_active: row.isActive });
}));
router.delete('/products/:productId/variants/:variantId/', asyncHandler(async (req, res) => { await prisma.productVariant.delete({ where: { id: Number(req.params.variantId) } }); res.json({ message: 'Variant deleted' }); }));

router.get('/products/:productId/gallery/', asyncHandler(async (req, res) => {
    const rows = await prisma.productImage.findMany({ where: { productId: Number(req.params.productId) }, orderBy: { sortOrder: 'asc' } });
    res.json(rows.map((row) => ({ id: row.id, image: row.image, alt_text: row.altText, sort_order: row.sortOrder })));
}));
router.post('/products/:productId/gallery/', upload.fields([{ name: 'image', maxCount: 1 }, { name: 'images', maxCount: 20 }]), asyncHandler(async (req, res) => {
    const files = [...(req.files?.image || []), ...(req.files?.images || [])];
    const created = [];
    for (const [i, file] of files.entries()) created.push(await prisma.productImage.create({ data: { productId: Number(req.params.productId), image: uploadedFileValue(file), altText: req.body[`alt_text_${i}`] || req.body.alt_text || '', sortOrder: Number(req.body[`sort_order_${i}`] || req.body.sort_order || i) } }));
    res.status(201).json(created.map((row) => ({ id: row.id, image: row.image, alt_text: row.altText, sort_order: row.sortOrder })));
}));
router.patch('/products/:productId/gallery/:imageId/', upload.single('image'), asyncHandler(async (req, res) => {
    const data = {};
    if ('alt_text' in req.body) data.altText = req.body.alt_text;
    if ('sort_order' in req.body) data.sortOrder = Number(req.body.sort_order || 0);
    if (req.file) data.image = uploadedFileValue(req.file);
    const row = await prisma.productImage.update({ where: { id: Number(req.params.imageId) }, data });
    res.json({ id: row.id, image: row.image, alt_text: row.altText, sort_order: row.sortOrder });
}));
router.delete('/products/:productId/gallery/:imageId/', asyncHandler(async (req, res) => { await prisma.productImage.delete({ where: { id: Number(req.params.imageId) } }); res.json({ message: 'Gallery image deleted' }); }));

router.get('/banners/', asyncHandler(async (req, res) => { const rows = await prisma.banner.findMany({ orderBy: [{ sortOrder: 'asc' }, { id: 'asc' }] }); res.json(rows.map(bannerPayload)); }));
router.post('/banners/', upload.single('image'), asyncHandler(async (req, res) => { const row = await prisma.banner.create({ data: { title: req.body.title || '', subtitle: req.body.subtitle || '', image: req.file ? uploadedFileValue(req.file) : (req.body.image || ''), linkUrl: req.body.link_url || '', bannerType: req.body.bannerType || req.body.banner_type || 'hero', active: boolFromBody(req.body.active, true), sortOrder: Number(req.body.sort_order || 0), productId: req.body.product ? Number(req.body.product) : null } }); res.status(201).json(bannerPayload(row)); }));
router.post('/banners/bulk/', upload.any(), asyncHandler(async (req, res) => { const data = typeof req.body.banners === 'string' ? JSON.parse(req.body.banners) : (req.body.banners || []); const created = []; for (const item of data) created.push(await prisma.banner.create({ data: { title: item.title || '', subtitle: item.subtitle || '', image: item.image || '', linkUrl: item.link_url || '', bannerType: item.banner_type || 'hero', active: item.active !== false, sortOrder: Number(item.sort_order || 0), productId: item.product ? Number(item.product) : null } })); res.status(201).json(created.map(bannerPayload)); }));
router.post('/banners/:id/', asyncHandler(async (req, res) => { const current = await prisma.banner.findUnique({ where: { id: Number(req.params.id) } }); const row = await prisma.banner.update({ where: { id: Number(req.params.id) }, data: { active: !current.active } }); res.json({ active: row.active }); }));
router.delete('/banners/:id/', asyncHandler(async (req, res) => { await prisma.banner.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Banner deleted' }); }));
router.post('/banners/:id/reorder/:direction/', asyncHandler(async (req, res) => res.json({ message: `Banner moved ${req.params.direction}` })));

router.get('/announcements/', asyncHandler(async (req, res) => { const rows = await prisma.announcement.findMany({ orderBy: { createdAt: 'desc' } }); res.json(rows.map((row) => ({ id: row.id, message: row.message, active: row.active, is_flash_sale: row.isFlashSale, created_at: row.createdAt }))); }));
router.post('/announcements/', asyncHandler(async (req, res) => { const row = await prisma.announcement.create({ data: { message: req.body.message || '', isFlashSale: boolFromBody(req.body.is_flash_sale), active: boolFromBody(req.body.active, true) } }); res.status(201).json({ id: row.id, message: row.message, active: row.active, is_flash_sale: row.isFlashSale, created_at: row.createdAt }); }));
router.post('/announcements/:id/toggle/', asyncHandler(async (req, res) => { const current = await prisma.announcement.findUnique({ where: { id: Number(req.params.id) } }); const row = await prisma.announcement.update({ where: { id: Number(req.params.id) }, data: { active: !current.active } }); res.json({ active: row.active }); }));
router.delete('/announcements/:id/', asyncHandler(async (req, res) => { await prisma.announcement.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Deleted' }); }));

router.get('/contact-messages/', asyncHandler(async (req, res) => { const rows = await prisma.contactMessage.findMany({ orderBy: { createdAt: 'desc' } }); res.json(rows.map((row) => ({ id: row.id, user: row.userId, name: row.name, email: row.email, subject: row.subject, message: row.message, reply: row.reply, status: row.status, created_at: row.createdAt, updated_at: row.updatedAt }))); }));
router.post('/contact-messages/:id/reply/', asyncHandler(async (req, res) => { await prisma.contactMessage.update({ where: { id: Number(req.params.id) }, data: { reply: req.body.reply || '', status: 'replied' } }); res.json({ message: 'Reply sent' }); }));
router.delete('/contact-messages/:id/delete/', asyncHandler(async (req, res) => { await prisma.contactMessage.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Message deleted' }); }));

router.get('/delivery-charges/', asyncHandler(async (req, res) => { const rows = await prisma.deliveryCharge.findMany({ include: { tiers: true }, orderBy: [{ province: 'asc' }, { city: 'asc' }] }); res.json(rows.map((row) => ({ id: row.id, province: row.province, city: row.city, charge: row.charge, min_order_for_free: row.minOrderForFree, is_active: row.isActive, effective_charge: row.charge, tiers: row.tiers.map((t) => ({ id: t.id, delivery_charge: t.deliveryChargeId, min_quantity: t.minQuantity, max_quantity: t.maxQuantity, charge: t.charge })), created_at: row.createdAt, updated_at: row.updatedAt }))); }));
router.post('/delivery-charges/', asyncHandler(async (req, res) => { const row = await prisma.deliveryCharge.create({ data: { province: req.body.province || 'Punjab', city: req.body.city || '', charge: new Prisma.Decimal(req.body.charge || 0), minOrderForFree: new Prisma.Decimal(req.body.min_order_for_free || 0), isActive: boolFromBody(req.body.is_active, true) }, include: { tiers: true } }); res.status(201).json(row); }));
router.patch('/delivery-charges/:id/', asyncHandler(async (req, res) => { const data = {}; if ('province' in req.body) data.province = req.body.province; if ('city' in req.body) data.city = req.body.city; if ('charge' in req.body) data.charge = new Prisma.Decimal(req.body.charge || 0); if ('min_order_for_free' in req.body) data.minOrderForFree = new Prisma.Decimal(req.body.min_order_for_free || 0); if ('is_active' in req.body) data.isActive = boolFromBody(req.body.is_active); const row = await prisma.deliveryCharge.update({ where: { id: Number(req.params.id) }, data, include: { tiers: true } }); res.json(row); }));
router.delete('/delivery-charges/:id/', asyncHandler(async (req, res) => { await prisma.deliveryCharge.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Deleted' }); }));
router.post('/delivery-charges/:deliveryChargeId/tiers/', asyncHandler(async (req, res) => { const row = await prisma.deliveryChargeTier.create({ data: { deliveryChargeId: Number(req.params.deliveryChargeId), minQuantity: Number(req.body.min_quantity || 1), maxQuantity: req.body.max_quantity ? Number(req.body.max_quantity) : null, charge: new Prisma.Decimal(req.body.charge || 0) } }); res.status(201).json({ id: row.id, delivery_charge: row.deliveryChargeId, min_quantity: row.minQuantity, max_quantity: row.maxQuantity, charge: row.charge }); }));
router.patch('/delivery-charges/tiers/:id/', asyncHandler(async (req, res) => { const data = {}; if ('min_quantity' in req.body) data.minQuantity = Number(req.body.min_quantity || 1); if ('max_quantity' in req.body) data.maxQuantity = req.body.max_quantity ? Number(req.body.max_quantity) : null; if ('charge' in req.body) data.charge = new Prisma.Decimal(req.body.charge || 0); const row = await prisma.deliveryChargeTier.update({ where: { id: Number(req.params.id) }, data }); res.json({ id: row.id, delivery_charge: row.deliveryChargeId, min_quantity: row.minQuantity, max_quantity: row.maxQuantity, charge: row.charge }); }));
router.delete('/delivery-charges/tiers/:id/', asyncHandler(async (req, res) => { await prisma.deliveryChargeTier.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Deleted' }); }));

router.get('/coupons/', asyncHandler(async (req, res) => {
    const where = {};
    if (req.query.is_gift && req.query.is_gift !== 'all') where.isGift = req.query.is_gift === 'true';
    const page = Math.max(1, Number(req.query.page || 1));
    const pageSize = Math.max(1, Number(req.query.page_size || 10));
    const [count, rows] = await Promise.all([
        prisma.coupon.count({ where }),
        prisma.coupon.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (page - 1) * pageSize, take: pageSize }),
    ]);
    res.json({ count, next: page * pageSize < count ? String(page + 1) : null, previous: page > 1 ? String(page - 1) : null, results: rows.map(couponSerializer) });
}));
router.post('/coupons/', asyncHandler(async (req, res) => {
    if (req.body.bulk_count) {
        const count = Math.min(500, Math.max(1, Number(req.body.bulk_count)));
        const batchId = `BATCH-${Date.now()}`;
        const rows = [];
        for (let i = 0; i < count; i += 1) rows.push(await createCouponFromBody(req.body, { code: randomCode('BULK', Number(req.body.token_length || 10)), isGift: true, autoGenerated: true, batchId }));
        return res.status(201).json({ count: rows.length, batch_id: batchId, results: rows.map(couponSerializer) });
    }
    if (req.body.assign_to_all) {
        const users = await prisma.user.findMany({ where: { isActive: true } });
        const batchId = `ALL-${Date.now()}`;
        const rows = [];
        for (const user of users) {
            const coupon = await createCouponFromBody(req.body, { code: randomCode('USER', Number(req.body.token_length || 10)), assignedToId: user.id, isGift: true, autoGenerated: true, batchId });
            await prisma.userNotification.create({ data: { userId: user.id, couponId: coupon.id, subject: 'New coupon available', body: `Your coupon code is ${coupon.code}` } });
            rows.push(coupon);
        }
        return res.status(201).json({ count: rows.length, email_sent: 0, batch_id: batchId, results: rows.map(couponSerializer) });
    }
    const row = await createCouponFromBody(req.body);
    res.status(201).json(couponSerializer(row));
}));
router.get('/coupons/export/', asyncHandler(async (req, res) => { const where = req.query.is_gift && req.query.is_gift !== 'all' ? { isGift: req.query.is_gift === 'true' } : {}; const rows = await prisma.coupon.findMany({ where, orderBy: { createdAt: 'desc' } }); res.type('text/csv').attachment('coupons.csv').send(['ID,Code,Discount Type,Discount Value,Is Active,Valid From,Valid Until', ...rows.map((c) => `${c.id},${c.code},${c.discountType},${c.discountValue},${c.isActive},${c.validFrom.toISOString()},${c.validTo.toISOString()}`)].join('\n')); }));
router.patch('/coupons/:id/', asyncHandler(async (req, res) => { const data = {}; if ('code' in req.body) data.code = req.body.code; if ('discount_type' in req.body) data.discountType = req.body.discount_type; if ('discount_value' in req.body) data.discountValue = decimalInput(req.body.discount_value); if ('min_order_amount' in req.body) data.minOrderAmount = decimalInput(req.body.min_order_amount); if ('max_uses' in req.body) data.maxUses = Number(req.body.max_uses || 0); if ('is_active' in req.body) data.isActive = boolFromBody(req.body.is_active); if ('valid_from' in req.body) data.validFrom = new Date(req.body.valid_from); if ('valid_to' in req.body) data.validTo = new Date(req.body.valid_to); if ('assigned_to' in req.body) data.assignedToId = req.body.assigned_to ? Number(req.body.assigned_to) : null; if ('description' in req.body) data.description = req.body.description; const row = await prisma.coupon.update({ where: { id: Number(req.params.id) }, data }); res.json(couponSerializer(row)); }));
router.delete('/coupons/:id/', asyncHandler(async (req, res) => { await prisma.coupon.delete({ where: { id: Number(req.params.id) } }); res.json({ message: 'Deleted' }); }));

router.get('/analytics/', asyncHandler(async (req, res) => {
    const [orderItems, users, orders] = await Promise.all([
        prisma.orderItem.findMany({ include: { product: { include: { category: true } } } }),
        prisma.user.findMany({ select: { dateJoined: true } }),
        prisma.order.findMany({ select: { createdAt: true } }),
    ]);
    const top = new Map(); const cats = new Map(); const usersByMonth = new Map(); const ordersByMonth = new Map();
    for (const item of orderItems) { const key = item.productId || 0; const cur = top.get(key) || { name: item.product?.name || 'Deleted product', id: key, total_qty: 0, total_revenue: 0 }; cur.total_qty += item.quantity; cur.total_revenue += Number(item.price) * item.quantity; top.set(key, cur); const cat = item.product?.category?.name || 'Uncategorized'; cats.set(cat, (cats.get(cat) || 0) + Number(item.price) * item.quantity); }
    for (const user of users) usersByMonth.set(monthKey(user.dateJoined), (usersByMonth.get(monthKey(user.dateJoined)) || 0) + 1);
    for (const order of orders) ordersByMonth.set(monthKey(order.createdAt), (ordersByMonth.get(monthKey(order.createdAt)) || 0) + 1);
    res.json({ top_products: [...top.values()].sort((a, b) => b.total_qty - a.total_qty).slice(0, 10), category_sales: [...cats.entries()].map(([category, total]) => ({ category, total })), users_per_month: [...usersByMonth.entries()].map(([month, count]) => ({ month, count })), orders_per_month: [...ordersByMonth.entries()].map(([month, count]) => ({ month, count })) });
}));
router.get('/reports/', asyncHandler(async (req, res) => {
    const orders = await prisma.order.findMany();
    const totalRevenue = orders.reduce((sum, o) => sum + Number(o.paidAmount || 0), 0);
    const totalDiscounts = orders.reduce((sum, o) => sum + Number(o.discountAmount || 0), 0);
    const payment = new Map(); const monthly = new Map();
    for (const order of orders) {
        const method = order.paymentMethod || 'Unknown';
        const pm = payment.get(method) || { method, count: 0, total: 0 };
        pm.count += 1; pm.total += Number(order.paidAmount || 0); payment.set(method, pm);
        const month = monthKey(order.createdAt);
        const ms = monthly.get(month) || { month, count: 0, total: 0 };
        ms.count += 1; ms.total += Number(order.paidAmount || 0); monthly.set(month, ms);
    }
    res.json({ total_revenue: totalRevenue, total_discounts: totalDiscounts, total_orders: orders.length, avg_order_value: orders.length ? totalRevenue / orders.length : 0, payment_methods: [...payment.values()], monthly_sales: [...monthly.values()].sort((a, b) => a.month.localeCompare(b.month)) });
}));

module.exports = router;
